{
  "cve": "CVE-2023-41040",
  "mitre": {
    "cpes": [],
    "created": "2023-08-30T21:07:42.263000+00:00",
    "description": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 4,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2023/41xxx/CVE-2023-41040.json",
    "references": [
      "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175",
      "https://github.com/gitpython-developers/GitPython/commit/74e55ee4544867e1bd976b7df5a45869ee397b0b",
      "https://github.com/gitpython-developers/GitPython/commit/e98f57b81f792f0f5e18d33ee658ae395f9aa3c4",
      "https://github.com/gitpython-developers/GitPython/pull/1672",
      "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37",
      "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
      "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-165.yaml",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html"
    ],
    "title": "GitPython blind local file inclusion",
    "updated": "2024-10-01T18:04:56.017000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-22"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:gitpython_project:gitpython:*:*:*:*:*:python:*:*"
    ],
    "created": "2023-08-30T22:15:09.857000+00:00",
    "description": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 6.5,
        "vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2023/CVE-2023-41040.json",
    "references": [
      "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175",
      "https://github.com/gitpython-developers/GitPython/commit/74e55ee4544867e1bd976b7df5a45869ee397b0b",
      "https://github.com/gitpython-developers/GitPython/commit/e98f57b81f792f0f5e18d33ee658ae395f9aa3c4",
      "https://github.com/gitpython-developers/GitPython/pull/1672",
      "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37",
      "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
      "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-165.yaml",
      "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html"
    ],
    "title": null,
    "updated": "2024-09-20T21:15:12.280000+00:00",
    "vendors": [
      "gitpython_project",
      "gitpython_project$PRODUCT$gitpython"
    ],
    "weaknesses": [
      "CWE-22"
    ]
  },
  "opencve": {
    "changes": [
      {
        "created": "2024-09-20T20:30:00+00:00",
        "data": [
          {
            "details": {
              "new": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.",
              "old": " GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has not yet been addressed."
            },
            "type": "description"
          },
          {
            "details": {
              "new": "GitPython blind local file inclusion",
              "old": "Blind local file inclusion in GitPython"
            },
            "type": "title"
          },
          {
            "details": {
              "added": [
                "https://github.com/gitpython-developers/GitPython/commit/74e55ee4544867e1bd976b7df5a45869ee397b0b",
                "https://github.com/gitpython-developers/GitPython/commit/e98f57b81f792f0f5e18d33ee658ae395f9aa3c4",
                "https://github.com/gitpython-developers/GitPython/pull/1672",
                "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37",
                "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-165.yaml"
              ],
              "removed": []
            },
            "type": "references"
          }
        ],
        "id": "d0ecfbad-af1c-47d5-9272-958e72827189"
      },
      {
        "created": "2024-10-01T18:30:00+00:00",
        "data": [
          {
            "details": {
              "added": {
                "ssvc": {
                  "options": {
                    "Automatable": "no",
                    "Exploitation": "poc",
                    "Technical Impact": "partial"
                  },
                  "version": "2.0.3"
                }
              },
              "removed": {},
              "updated": {}
            },
            "type": "metrics"
          }
        ],
        "id": "45bfc1e1-76ac-4dfc-968d-334d0239fb12"
      }
    ],
    "cpes": {
      "data": [
        "cpe:/a:redhat:ansible_automation_platform:2.4::el8",
        "cpe:/a:redhat:ansible_automation_platform:2.4::el9",
        "cpe:/a:redhat:openstack:17.1::el8",
        "cpe:/a:redhat:openstack:17.1::el9",
        "cpe:/a:redhat:satellite:6.14::el8",
        "cpe:/a:redhat:satellite_capsule:6.14::el8",
        "cpe:2.3:a:gitpython_project:gitpython:*:*:*:*:*:python:*:*"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "created": {
      "data": "2023-08-30T21:07:42.263000+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 4,
          "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {
          "options": {
            "Automatable": "no",
            "Exploitation": "poc",
            "Technical Impact": "partial"
          },
          "version": "2.0.3"
        },
        "provider": "vulnrichment"
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175",
        "https://github.com/gitpython-developers/GitPython/commit/74e55ee4544867e1bd976b7df5a45869ee397b0b",
        "https://github.com/gitpython-developers/GitPython/commit/e98f57b81f792f0f5e18d33ee658ae395f9aa3c4",
        "https://github.com/gitpython-developers/GitPython/pull/1672",
        "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.37",
        "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
        "https://github.com/pypa/advisory-database/tree/main/vulns/gitpython/PYSEC-2023-165.yaml",
        "https://lists.debian.org/debian-lts-announce/2023/09/msg00036.html",
        "https://nvd.nist.gov/vuln/detail/CVE-2023-41040",
        "https://www.cve.org/CVERecord?id=CVE-2023-41040"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "GitPython blind local file inclusion",
      "provider": "mitre"
    },
    "updated": {
      "data": "2024-10-01T18:04:56.017000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "gitpython_project",
        "gitpython_project$PRODUCT$gitpython",
        "redhat",
        "redhat$PRODUCT$ansible_automation_platform",
        "redhat$PRODUCT$openstack",
        "redhat$PRODUCT$satellite",
        "redhat$PRODUCT$satellite_capsule"
      ],
      "providers": [
        "nvd",
        "redhat"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-22"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [
      "cpe:/a:redhat:ansible_automation_platform:2.4::el8",
      "cpe:/a:redhat:ansible_automation_platform:2.4::el9",
      "cpe:/a:redhat:openstack:17.1::el8",
      "cpe:/a:redhat:openstack:17.1::el9",
      "cpe:/a:redhat:satellite:6.14::el8",
      "cpe:/a:redhat:satellite_capsule:6.14::el8"
    ],
    "created": "2023-08-31T00:00:00+00:00",
    "description": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5.1,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
      },
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2023/CVE-2023-41040.json",
    "references": [
      "https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-cwvm-v4w8-q58c",
      "https://nvd.nist.gov/vuln/detail/CVE-2023-41040",
      "https://www.cve.org/CVERecord?id=CVE-2023-41040"
    ],
    "title": "GitPython: Blind local file inclusion",
    "updated": "2023-08-31T00:00:00+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$ansible_automation_platform",
      "redhat$PRODUCT$openstack",
      "redhat$PRODUCT$satellite",
      "redhat$PRODUCT$satellite_capsule"
    ],
    "weaknesses": [
      "CWE-22"
    ]
  },
  "vulnrichment": {
    "cpes": [],
    "created": "2023-08-30T21:07:42.263000+00:00",
    "description": "GitPython is a python library used to interact with Git repositories. In order to resolve some git references, GitPython reads files from the `.git` directory, in some places the name of the file being read is provided by the user, GitPython doesn't check if this file is located outside the `.git` directory. This allows an attacker to make GitPython read any file from the system. This vulnerability is present in https://github.com/gitpython-developers/GitPython/blob/1c8310d7cae144f74a671cbe17e51f63a830adbf/git/refs/symbolic.py#L174-L175. That code joins the base directory with a user given string without checking if the final path is located outside the base directory. This vulnerability cannot be used to read the contents of files but could in theory be used to trigger a denial of service for the program. This issue has been addressed in version 3.1.37.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {},
      "kev": {},
      "ssvc": {
        "options": {
          "Automatable": "no",
          "Exploitation": "poc",
          "Technical Impact": "partial"
        },
        "version": "2.0.3"
      }
    },
    "references": [],
    "title": "GitPython blind local file inclusion",
    "updated": "2024-10-01T18:04:52.308000+00:00",
    "vendors": [],
    "vulnrichment_repo_path": "2023/41xxx/CVE-2023-41040.json",
    "weaknesses": []
  }
}