{
  "cve": "CVE-2018-11102",
  "mitre": {
    "cpes": [],
    "created": "2018-05-15T02:00:00+00:00",
    "description": "An issue was discovered in Libav 12.3. A read access violation in the mov_probe function in libavformat/mov.c allows remote attackers to cause a denial of service (application crash), as demonstrated by avconv.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2018/11xxx/CVE-2018-11102.json",
    "references": [
      "https://bugzilla.libav.org/show_bug.cgi?id=1128",
      "https://docs.google.com/document/d/18xCwfxMSJiQ9ruQSVaO8-jlcobDjFiYXWOaw31V37xo/edit",
      "https://lists.debian.org/debian-lts-announce/2019/09/msg00000.html"
    ],
    "title": null,
    "updated": "2024-08-05T07:54:36.542000+00:00",
    "vendors": [],
    "weaknesses": []
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:libav:libav:12.3:*:*:*:*:*:*:*"
    ],
    "created": "2018-05-15T02:29:00.207000+00:00",
    "description": "An issue was discovered in Libav 12.3. A read access violation in the mov_probe function in libavformat/mov.c allows remote attackers to cause a denial of service (application crash), as demonstrated by avconv.",
    "metrics": {
      "cvssV2_0": {
        "score": 5.0,
        "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
      },
      "cvssV3_0": {
        "score": 7.5,
        "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
      },
      "cvssV3_1": {},
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2018/CVE-2018-11102.json",
    "references": [
      "https://bugzilla.libav.org/show_bug.cgi?id=1128",
      "https://docs.google.com/document/d/18xCwfxMSJiQ9ruQSVaO8-jlcobDjFiYXWOaw31V37xo/edit",
      "https://lists.debian.org/debian-lts-announce/2019/09/msg00000.html"
    ],
    "title": null,
    "updated": "2019-09-02T11:15:11.310000+00:00",
    "vendors": [
      "libav",
      "libav$PRODUCT$libav"
    ],
    "weaknesses": [
      "CWE-119"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:libav:libav:12.3:*:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2018-05-15T02:00:00+00:00",
      "provider": "mitre"
    },
    "description": {
      "data": "An issue was discovered in Libav 12.3. A read access violation in the mov_probe function in libavformat/mov.c allows remote attackers to cause a denial of service (application crash), as demonstrated by avconv.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 5.0,
          "vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {
          "score": 7.5,
          "vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
        },
        "provider": "nvd"
      },
      "cvssV3_1": {
        "data": {},
        "provider": null
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": null,
        "provider": null
      }
    },
    "references": {
      "data": [
        "https://bugzilla.libav.org/show_bug.cgi?id=1128",
        "https://docs.google.com/document/d/18xCwfxMSJiQ9ruQSVaO8-jlcobDjFiYXWOaw31V37xo/edit",
        "https://lists.debian.org/debian-lts-announce/2019/09/msg00000.html"
      ],
      "providers": [
        "mitre",
        "nvd"
      ]
    },
    "title": {
      "data": null,
      "provider": null
    },
    "updated": {
      "data": "2024-08-05T07:54:36.542000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "libav",
        "libav$PRODUCT$libav"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-119"
      ],
      "providers": [
        "nvd"
      ]
    }
  }
}