{
  "cve": "CVE-2020-25635",
  "mitre": {
    "cpes": [],
    "created": "2020-10-05T13:23:33+00:00",
    "description": "A flaw was found in Ansible Base when using the aws_ssm connection plugin as garbage collector is not happening after playbook run is completed. Files would remain in the bucket exposing the data. This issue affects directly data confidentiality.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N"
      },
      "cvssV4_0": {}
    },
    "mitre_repo_path": "cves/2020/25xxx/CVE-2020-25635.json",
    "references": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25635",
      "https://github.com/ansible-collections/community.aws/issues/222"
    ],
    "title": null,
    "updated": "2024-08-04T15:40:36.458000+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-212"
    ]
  },
  "nvd": {
    "cpes": [
      "cpe:2.3:a:redhat:ansible:2.10.1:rc2:*:*:*:*:*:*"
    ],
    "created": "2020-10-05T14:15:13.217000+00:00",
    "description": "A flaw was found in Ansible Base when using the aws_ssm connection plugin as garbage collector is not happening after playbook run is completed. Files would remain in the bucket exposing the data. This issue affects directly data confidentiality.",
    "metrics": {
      "cvssV2_0": {
        "score": 2.1,
        "vector": "AV:L/AC:L/Au:N/C:P/I:N/A:N"
      },
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5.5,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N"
      },
      "cvssV4_0": {}
    },
    "nvd_repo_path": "2020/CVE-2020-25635.json",
    "references": [
      "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25635",
      "https://github.com/ansible-collections/community.aws/issues/222"
    ],
    "title": null,
    "updated": "2023-11-07T03:20:17.723000+00:00",
    "vendors": [
      "redhat",
      "redhat$PRODUCT$ansible"
    ],
    "weaknesses": [
      "CWE-212"
    ]
  },
  "opencve": {
    "changes": [],
    "cpes": {
      "data": [
        "cpe:2.3:a:redhat:ansible:2.10.1:rc2:*:*:*:*:*:*"
      ],
      "providers": [
        "nvd"
      ]
    },
    "created": {
      "data": "2020-09-04T00:00:00+00:00",
      "provider": "redhat"
    },
    "description": {
      "data": "A flaw was found in Ansible Base when using the aws_ssm connection plugin as garbage collector is not happening after playbook run is completed. Files would remain in the bucket exposing the data. This issue affects directly data confidentiality.",
      "provider": "mitre"
    },
    "metrics": {
      "cvssV2_0": {
        "data": {
          "score": 2.1,
          "vector": "AV:L/AC:L/Au:N/C:P/I:N/A:N"
        },
        "provider": "nvd"
      },
      "cvssV3_0": {
        "data": {},
        "provider": null
      },
      "cvssV3_1": {
        "data": {
          "score": 5,
          "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N"
        },
        "provider": "mitre"
      },
      "cvssV4_0": {
        "data": {},
        "provider": null
      },
      "kev": {
        "data": {},
        "provider": null
      },
      "ssvc": {
        "data": {},
        "provider": null
      },
      "threat_severity": {
        "data": "Moderate",
        "provider": "redhat"
      }
    },
    "references": {
      "data": [
        "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-25635",
        "https://github.com/ansible-collections/community.aws/issues/222",
        "https://nvd.nist.gov/vuln/detail/CVE-2020-25635",
        "https://www.cve.org/CVERecord?id=CVE-2020-25635"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    },
    "title": {
      "data": "Collections: aws_ssm connection plugin should garbage collect the s3 bucket after the file transfers",
      "provider": "nvd"
    },
    "updated": {
      "data": "2024-08-04T15:40:36.458000+00:00",
      "provider": "mitre"
    },
    "vendors": {
      "data": [
        "redhat",
        "redhat$PRODUCT$ansible"
      ],
      "providers": [
        "nvd"
      ]
    },
    "weaknesses": {
      "data": [
        "CWE-212"
      ],
      "providers": [
        "mitre",
        "nvd",
        "redhat"
      ]
    }
  },
  "redhat": {
    "cpes": [],
    "created": "2020-09-04T00:00:00+00:00",
    "description": "A flaw was found in Ansible Base when using the aws_ssm connection plugin as garbage collector is not happening after playbook run is completed. Files would remain in the bucket exposing the data. This issue affects directly data confidentiality.",
    "metrics": {
      "cvssV2_0": {},
      "cvssV3_0": {},
      "cvssV3_1": {
        "score": 5.0,
        "vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N"
      },
      "threat_severity": "Moderate"
    },
    "redhat_repo_path": "2020/CVE-2020-25635.json",
    "references": [
      "https://github.com/ansible-collections/community.aws/issues/222",
      "https://nvd.nist.gov/vuln/detail/CVE-2020-25635",
      "https://www.cve.org/CVERecord?id=CVE-2020-25635"
    ],
    "title": "Collections: aws_ssm connection plugin should garbage collect the s3 bucket after the file transfers",
    "updated": "2020-09-04T00:00:00+00:00",
    "vendors": [],
    "weaknesses": [
      "CWE-212"
    ]
  }
}